spring.application.name=arbor
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=public

spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.default-schema=public
spring.flyway.baseline-on-migrate=false

spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:10}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_IDLE:2}
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000


brevo.api.key=${BREVO_API_KEY:}
brevo.sender.email=${BREVO_SENDER_EMAIL:}

jwt.secret=${JWT_SECRET}

server.forward-headers-strategy=framework

logging.level.root=${LOG_LEVEL:INFO}
logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework.security=INFO

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.mail.enabled=false
