# Nome do projeto e porta do servidor
spring.application.name=arbor
server.port=8080

# Configuracao de conexao com o banco PostGIS (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/arbor_db
spring.datasource.username=arbor_user
spring.datasource.password=arbor_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao do JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Desabilitar Flyway (Hibernate cria as tabelas automaticamente)
spring.flyway.enabled=false